# Generated by Django 4.2.11 on 2024-05-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Napravlenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sphere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Startapps_and_projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_published", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "header",
                    models.CharField(max_length=255, verbose_name="Руководитель"),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("no_experience", "Нет опыта"),
                            ("1-3", "1-3 года"),
                            ("3-5", "3-5 лет"),
                            ("5", "5+"),
                        ],
                        max_length=30,
                        verbose_name="Опыт работы",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("bakalavriat", "Бакалавриат"),
                            ("magistr", "Магистратура"),
                            ("aspirantyra", "Аспирантура"),
                        ],
                        max_length=100,
                        verbose_name="Уровень образования",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/%Y/%m/%d/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "applied_users",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество человек"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="itmo_hh.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="itmo_hh.sphere",
                        verbose_name="Сфера деятельности",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resumes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("time_published", models.DateTimeField(auto_now_add=True)),
                ("FIO", models.CharField(max_length=255, verbose_name="ФИО")),
                ("sex", models.CharField(max_length=30, verbose_name="Пол")),
                ("birthday", models.DateField(verbose_name="День рождения")),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("bakalavriat", "Бакалавриат"),
                            ("magistr", "Магистратура"),
                            ("aspirantyra", "Аспирантура"),
                        ],
                        max_length=100,
                        verbose_name="Уровень образования",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("no_experience", "Нет опыта"),
                            ("1-3", "1-3 года"),
                            ("3-5", "3-5 лет"),
                            ("5", "5+"),
                        ],
                        max_length=30,
                        verbose_name="Опыт",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/%Y/%m/%d/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "napravlenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="itmo_hh.napravlenie",
                        verbose_name="Направление обучения",
                    ),
                ),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="itmo_hh.sphere",
                        verbose_name="Сфера деятельности",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_invitation",
                        to="itmo_hh.startapps_and_projects",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes_invitation",
                        to="itmo_hh.resumes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_application",
                        to="itmo_hh.startapps_and_projects",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes_application",
                        to="itmo_hh.resumes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="My_otclics_and_offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_published", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "id_offer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_to_whom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_whom_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Love",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_love_proj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itmo_hh.startapps_and_projects",
                    ),
                ),
                (
                    "id_love_res",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="itmo_hh.resumes",
                    ),
                ),
            ],
        ),
    ]
