# Generated by Django 4.2.11 on 2024-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itmo_hh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="time_published",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="time_published",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumes",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="День рождения"),
        ),
        migrations.AlterField(
            model_name="resumes",
            name="sex",
            field=models.CharField(
                choices=[("women", "Женский"), ("men", "Мужской")],
                max_length=30,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="startapps_and_projects",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("bakalavriat", "Бакалавриат"),
                    ("magistr", "Магистратура"),
                    ("aspirantyra", "Аспирантура"),
                ],
                max_length=100,
                verbose_name="Требуемый уровень образования",
            ),
        ),
        migrations.AlterField(
            model_name="startapps_and_projects",
            name="experience",
            field=models.CharField(
                choices=[
                    ("no_experience", "Нет опыта"),
                    ("1-3", "1-3 года"),
                    ("3-5", "3-5 лет"),
                    ("5", "5+ лет"),
                ],
                max_length=30,
                verbose_name="Необходимый опыт работы",
            ),
        ),
    ]
