# Generated by Django 4.2.11 on 2024-04-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name="startapps_and_projects",
            name="applied_users",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
